### ISSUE TITLE
ValidationException during asset creation after deployment

### ISSUE THREAD

**Issue by sathish0804** [aws-solutions-library-samples/guidance-for-data-fabric-on-aws#6]
After deploying the repository and attempting to create an asset,
![image](https://github.com/user-attachments/assets/a393d17d-74ba-4dc6-b0a2-38fc89d4cda9)

 I encountered the following error:
`{
  "errorType": "ValidationException",
  "errorMessage": "Environment GB_DL_ENV does not allow publishing from the selected database. The allowed publisher Database is gb_dl_env_pub_db",
  "trace": [
    "ValidationException: Environment GB_DL_ENV does not allow publishing from the selected database. The allowed publisher Database is gb_dl_env_pub_db",
    "    at de_ValidationExceptionRes (file:///var/task/index.mjs:390:169438)",
    "    at de_CommandError (file:///var/task/index.mjs:390:167494)",
    "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "    at async file:///var/task/index.mjs:357:313373",
    "    at async file:///var/task/index.mjs:366:1240",
    "    at async file:///var/task/index.mjs:365:15893",
    "    at async file:///var/task/index.mjs:327:73196",
    "    at async file:///var/task/index.mjs:357:277658",
    "    at async Gre.process (file:///var/task/index.mjs:418:42574)",
    "    at async Runtime.l8i [as handler] (file:///var/task/index.mjs:440:7950)"
  ]
}
`
ValidationException: Environment GB_DL_ENV does not allow publishing from the selected database. The allowed publisher Database is gb_dl_env_pub_db.
![image](https://github.com/user-attachments/assets/bf930d08-b4cd-423b-bf53-bedfdb54e9dd)

Steps to Reproduce:
Deployed the repository following the provided guidelines.
Tried creating an asset.
Encountered the error mentioned above.
Expected Behavior: Asset creation should proceed without validation issues.

Environment:
AWS services used
Relevant configurations

**Comment by johnrotach** [comment]
Hello. Can you please provide the request body you used when creating the asset?

**Comment by sathish0804** [comment]
Below is the request body that was used when creating the asset:
![image](https://github.com/user-attachments/assets/3ca64d08-6252-4ea3-912a-dcfb7590b054)

**Comment by johnrotach** [comment]
Hey - thanks for this. I was hoping to see what the actual values you used to swap into the `catalog` section of the request. I want to validate those look good before looking deeper into the logs.
